### ISSUE TITLE
samenvattende adresnotatie werkt nog niet bij overlappende ranges van huisnummers 

### ISSUE THREAD

**Issue by astridvanhumbeeck** [OnroerendErfgoed/housenum-be-r-parser#9]
Aanvulling op https://github.com/OnroerendErfgoed/inventaris/issues/2430

Bij overlappende ranges van meerdere locatie-elementen wordt adressamenvatting nog niet correct gemaakt.

VB:
lijn 1: range 1-11, lijn2: range 5-9 resulteert in 1-5, 5-7, 7-9, 9-11 omdat de dubbels daar niet uit worden gehaald. Dat is iets binnen https://github.com/OnroerendErfgoed/housenum-be-r-parser/issues/ dat moet gefixt worden.

_Originally posted by @Wim-De-Clercq in https://github.com/OnroerendErfgoed/inventaris/issues/2430#issuecomment-522915844_

**Comment by astridvanhumbeeck** [comment]
Moet hier ook nog iets voor gebeuren bij code van inventaris? Daar heb ik nu nog geen ticket aangemaakt

**Comment by Wim-De-Clercq** [comment]
Na bugfix release van dit moet er 1 lijn veranderen in inventaris om de versie van `housenum-be-r parser` te verhogen.

**Comment by Wim-De-Clercq** [comment]
TODO:
Ik denk dat als we voor de `sort` hier https://github.com/OnroerendErfgoed/housenum-be-r-parser/blob/d598e9ee1e60058d4d81a2c73b8af26e7cbb8e27/housenumparser/merger.py#L148
De dubbels eruithalen eerst mbv een `set` dat het zal werken.
Ook test toevoegen met bovenstaande ranges en zien dat huidige testen niet veranderen van gedrag.

**Comment by axd1967** [comment]
aha - is er een verband met https://github.com/OnroerendErfgoed/inventaris/issues/2625 ?

**Comment by Wim-De-Clercq** [comment]
Neen, dat is deel van https://github.com/OnroerendErfgoed/inventaris/issues/2430 Maar die issue is deel van release 1.1.0 en dus nog niet gedeployed.
